# Run scenario 1: Cross-sectoral, European view
# Grid planning is realized both cross-border and cross-sectoral

run:
  name: "2025-MM-DD-branch-2190SEG-CE-DSR"
  disable_progressbar: true
  shared_resources: false
  shared_cutouts: true

scenario:
  sector_opts:
  - 2190SEG-T-H-B-I-A
  planning_horizons:
  - 2020
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050

sector:
  v2g: true
  bev_dsm: true
  bev_availability: 0.5
  bev_energy: 0.05
  bev_charge_efficiency: 0.9
  bev_plug_to_wheel_efficiency: 0.2
  bev_charge_rate: 0.011
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  bev_dsm_restriction_value: 0.75
  bev_dsm_restriction_time: 7

policy_plans:
  include_tyndp_elec:
    enable: true
    allowed_statuses:
    - under construction
  include_tyndp_gas:
    enable: true
    allowed_statuses:
    - FID   # Final investment decision
  agg_p_nom_limits: data/agg_p_nom_minmax_european.csv

solving:
  oetc:
    enabled: false # enable solving via Open Energy Transition Cloud (OETC)
  solver:
    name: gurobi
    options: gurobi-default
