# Sensitivity with limited fossil gas and oil use: Cross-sectoral, European view

run:
  name: "2025-MM-DD-branch-2190SEG-CE-no-gas-no-oil"
  disable_progressbar: true
  shared_resources: false
  shared_cutouts: true

scenario:
  sector_opts:
  - 2190SEG-T-H-B-I-A
  planning_horizons:
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050

policy_plans:
  include_tyndp_elec:
    enable: true
    allowed_statuses:
      - under construction
  include_tyndp_gas:
    enable: true
    allowed_statuses:
      - FID # Final investment decision
  agg_p_nom_limits: data/agg_p_nom_minmax_european.csv

sensitivities:
  no_gas_no_oil: True

solving:
  solver:
    name: gurobi
    options: gurobi-default
