name: Docs CI

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - closed
    branches:
    - main

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      if: github.event.action != 'closed'
      run: sudo apt-get install -y libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libfontconfig1

    - name: Install dependencies
      if: github.event.action != 'closed'
      run: pip install -r docs/requirements.txt

    - name: Build docs
      if: github.event.action != 'closed'
      run: mkdocs build --strict
      env:
        BUILD_PDF: "1"

    - name: Deploy PR preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: site/
        preview-branch: gh-pages
        umbrella-dir: pr-preview
